---
- name: simple-provisioning
  hosts: localhost
  connenction: local
  gather_facts:false
  vars:
    aws_region: ap-norheast-2
	vpc_name: simple-vpc
	vpc_cidr_block: 10.210.0.0/16
	subnet_cidr_block: 10.210.1.0/24
	instance_image:ami-06098fd00463352b6
    ec2_key_name: btc-user34
	instance_type: t3.nano
	
	tasks:
	- name: create vpc
	ec2_vpc_net:
	  name: "{{ vpc.name }}"
	  cidr_block: "{{ vpc_cidr_block}}"
	  region: "{{aws_region}}"
	  tags:
	    name: "{{ vpc.name }}"
      tenancy: default
	register: result_vpc